async function pos(){await saleScreen({mode:'takeaway'})}
async function saleScreen({mode='takeaway',table=null,order=null}={}){
  title(mode==='dinein'?`الصالة — ${table?.name||''}`:'الكاشير');await Promise.all([loadCatalog(),refreshSettings()]);let cat='all';let cart=(order?.items||[]).map(i=>({id:i.product_id,name:i.product_name,price:Number(i.unit_price),qty:Number(i.qty),notes:i.notes||''}));let notes=order?.notes||'';
  const draw=()=>{const prods=cat==='all'?S.products:S.products.filter(p=>p.category_id===cat);const total=cart.reduce((s,x)=>s+x.qty*x.price,0);$('#content').innerHTML=`<div class="pos-layout"><div class="card catalog"><div class="section-title"><div><h3>${mode==='dinein'?'طلب '+esc(table.name):'الأصناف'}</h3>${order?`<span class="badge amber">طلب #${order.order_no}</span>`:''}</div><input id="ps" class="input search-box" placeholder="بحث عن صنف"></div><div class="category-bar"><button class="category-btn ${cat==='all'?'active':''}" data-cat="all">الكل</button>${S.cats.map(c=>`<button class="category-btn ${cat===c.id?'active':''}" data-cat="${c.id}">${esc(c.name)}</button>`).join('')}</div><div class="products">${prods.map(p=>`<button class="product" data-product="${p.id}"><strong>${esc(p.name)}</strong><span class="muted">${esc(p.category_name||'')}</span><span class="price">${money(p.price)}</span></button>`).join('')||'<div class="empty">أضف أصناف من لوحة الإدارة</div>'}</div></div><div class="card cart"><div class="order-modes">${mode==='dinein'?'<button id="backHall" class="btn btn-ghost">العودة للصالة</button>':`<button class="btn btn-cyan">تيك أواي</button>${S.settings.enable_dinein!==false?'<button class="btn" data-mode="hall">صالة</button>':''}${S.settings.enable_delivery!==false?'<button class="btn" data-mode="delivery">دليفري</button>':''}`}</div><div class="cart-items">${cart.map((i,k)=>`<div class="cart-row"><div><b>${esc(i.name)}</b><div class="muted">${money(i.price)}</div></div><div class="qty"><button data-minus="${k}">−</button><b>${i.qty}</b><button data-plus="${k}">+</button></div><div>${money(i.qty*i.price)}</div></div>`).join('')||'<div class="empty">اختر الأصناف من القائمة</div>'}</div><div class="field compact"><label>ملاحظات الطلب</label><input id="saleNotes" class="input" value="${esc(notes)}"></div><div class="field compact"><label>طريقة الدفع</label><select id="pay" class="select">${S.payments.map(p=>`<option value="${esc(p.code)}" ${p.code===(order?.payment_method||'cash')?'selected':''}>${esc(p.name)}</option>`).join('')}</select></div><div class="cart-total"><div class="total-line"><span>الإجمالي</span><span class="grand">${money(total)}</span></div>${mode==='dinein'?'<div class="dual-actions"><button id="hold" class="btn btn-cyan">حفظ على الطاولة</button><button id="finish" class="btn btn-green">تحصيل وإغلاق</button></div>':'<button id="finish" class="btn btn-primary btn-block">تحصيل وإتمام البيع</button>'}</div></div></div>`;
    $$('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;notes=$('#saleNotes')?.value||notes;draw()});$$('[data-product]').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>x.id===b.dataset.product),e=cart.find(x=>x.id===p.id);e?e.qty++:cart.push({id:p.id,name:p.name,price:Number(p.price),qty:1});notes=$('#saleNotes')?.value||notes;draw()});$$('[data-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.plus].qty++;notes=$('#saleNotes')?.value||notes;draw()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;cart[i].qty--;if(cart[i].qty<=0)cart.splice(i,1);notes=$('#saleNotes')?.value||notes;draw()});$('#ps').oninput=e=>$$('[data-product]').forEach(b=>b.style.display=b.textContent.includes(e.target.value)?'':'');$$('[data-mode]').forEach(b=>b.onclick=()=>go(b.dataset.mode));if($('#backHall'))$('#backHall').onclick=()=>go('hall');
    const payload=status=>({order_type:mode,table_id:table?.id||null,user_id:S.user.id,shift_id:S.shift?.id||null,status,paid:status==='closed'?total:0,payment_method:$('#pay')?.value||'cash',notes:$('#saleNotes')?.value||'',items:cart.map(x=>({product_id:x.id,product_name:x.name,qty:x.qty,unit_price:x.price,notes:x.notes||''}))});
    const save=async status=>{if(!S.shift)return toast('افتح وردية أولاً',true);if(!cart.length)return toast('أضف صنفاً واحداً على الأقل',true);try{const wasExisting=Boolean(order?.id);const o=order?await window.geek.orders.save(order.id,payload(status)):await window.geek.orders.create(payload(status));order=o;const stage=status==='closed'?(wasExisting?'final':'closed'):'open';const pr=await window.geek.printers.route(o.id,stage);if(pr.count&&!pr.success)toast('تم حفظ الطلب مع وجود مشكلة في إحدى الطابعات',true);toast(status==='closed'?`تم إغلاق الطلب #${o.order_no}`:`تم حفظ الطلب على ${table.name}`);if(status==='closed'){cart=[];return mode==='dinein'?go('hall'):draw()}draw()}catch(e){toast(e.message,true)}};
    if($('#hold'))$('#hold').onclick=()=>save('open');$('#finish').onclick=()=>save('closed');
  };draw();
}

async function hall(){title('الصالة');if(S.settings.enable_dinein===false){$('#content').innerHTML='<div class="card empty">الصالة غير مفعلة من لوحة الإدارة</div>';return}const tables=await window.geek.tables.list();$('#content').innerHTML=`<div class="section-title"><div><h3>خريطة الصالة</h3><span class="muted">اضغط على أي طاولة لفتح الطلب أو استكماله</span></div><button id="manageTables" class="btn btn-ghost btn-sm">إدارة الطاولات</button></div><div class="tables-grid">${tables.map(t=>`<button class="table-tile ${t.open_order_id?'occupied':'free'}" data-table="${t.id}"><div class="table-icon">▦</div><strong>${esc(t.name)}</strong><small>${esc(t.area||'الصالة')} · ${t.seats} مقاعد</small><span>${t.open_order_id?`طلب #${t.open_order_no} · ${money(t.open_total)}`:'متاحة'}</span></button>`).join('')||'<div class="card empty">لا توجد طاولات. أضفها من لوحة الإدارة.</div>'}</div>`;$$('[data-table]').forEach(b=>b.onclick=async()=>{const t=tables.find(x=>x.id===b.dataset.table),o=await window.geek.tables.order(t.id);saleScreen({mode:'dinein',table:t,order:o})});$('#manageTables').onclick=()=>{S.adminTab='tables';go('admin')}}

