const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={boot:null,user:null,page:'dashboard',cats:[],products:[],cart:[],deliveryTab:'orders',shift:null,selected:null};
const AR={new:'جديد',kitchen:'في المطبخ',ready:'جاهز',with_driver:'مع الطيار',awaiting_settlement:'بانتظار التسوية',closed:'مغلق',returned:'مرتجع'};
const TYPE={takeaway:'تيك أواي',dinein:'صالة',delivery:'دليفري'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number(v||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2})+' ج.م';
function toast(m,bad=false){const t=$('#toast');t.textContent=m;t.className='toast show'+(bad?' error':'');setTimeout(()=>t.className='toast',2600)}
function roleAllowed(p){if(!S.user)return false;if(S.user.role==='administrator'||S.user.role==='admin')return true;return ['dashboard','pos','delivery','shift'].includes(p)}
async function loadCatalog(){S.cats=await window.geek.categories();S.products=await window.geek.products()}
async function boot(){
  S.boot=await window.geek.bootstrap();
  if(!S.boot.licensed)return activation();
  if(!S.boot.hasUsers)return firstUser();
  login();
}
function activation(){
  $('#root').innerHTML=`<section class="auth-shell"><div class="auth-card"><img class="brand-logo" src="logo.jpg"><h1>تفعيل Geek POS</h1><p>يلزم الإنترنت للتفعيل مرة واحدة فقط. بعد ذلك يعمل التطبيق Offline.</p><div class="field"><label>مفتاح التفعيل</label><input id="lk" class="input" dir="ltr" placeholder="GEEK-XXXX-XXXX-XXXX-XXXX-XXXX"></div><button id="act" class="btn btn-primary btn-block">تفعيل النسخة</button><p style="margin-top:18px;font-size:13px">في حالة خطأ المفتاح تواصل مع الإدارة المالكة للتطبيق لشراء نسخة.</p></div></section>`;
  $('#act').onclick=async()=>{const r=await window.geek.activate($('#lk').value);if(!r.success)return toast(r.message,true);toast(r.message);S.boot=await window.geek.bootstrap();firstUser()}
}
function firstUser(){
  $('#root').innerHTML=`<section class="auth-shell"><div class="auth-card"><img class="brand-logo" src="logo.jpg"><h1>إنشاء مدير النشاط</h1><p>لا توجد كلمة مرور افتراضية.</p><div class="field"><label>الاسم</label><input id="n" class="input"></div><div class="field"><label>اسم المستخدم</label><input id="u" class="input" dir="ltr"></div><div class="field"><label>كلمة المرور</label><input id="p" type="password" class="input" dir="ltr"></div><button id="mk" class="btn btn-primary btn-block">إنشاء الحساب</button></div></section>`;
  $('#mk').onclick=async()=>{try{await window.geek.createFirstUser({name:$('#n').value,username:$('#u').value,password:$('#p').value});toast('تم إنشاء الحساب');login()}catch(e){toast(e.message,true)}}
}
function login(){
  $('#root').innerHTML=`<section class="auth-shell"><div class="auth-card"><img class="brand-logo" src="logo.jpg"><h1>Geek POS</h1><p>نظام إدارة نقاط البيع</p><div class="field"><label>اسم المستخدم</label><input id="lu" class="input" dir="ltr"></div><div class="field"><label>كلمة المرور</label><input id="lp" type="password" class="input" dir="ltr"></div><button id="go" class="btn btn-primary btn-block">دخول</button></div></section>`;
  $('#go').onclick=async()=>{const u=await window.geek.login($('#lu').value,$('#lp').value);if(!u)return toast('بيانات الدخول غير صحيحة',true);S.user=u;S.shift=await window.geek.shifts.current(u.id);await loadCatalog();shell()}
}
function nav(){
  const x=[['dashboard','⌂','الرئيسية'],['pos','▣','الكاشير'],['delivery','⌁','الدليفري'],['shift','◷','الورديات'],['reports','◫','التقارير'],['products','◇','الأقسام والأصناف'],['users','♙','المستخدمون'],['settings','⚙','الإعدادات'],['cloud','☁','اللوحة السحابية']];
  return x.filter(a=>roleAllowed(a[0])).map(a=>`<button data-page="${a[0]}"><span class="icon">${a[1]}</span><span class="label">${a[2]}</span></button>`).join('');
}
function shell(){
  $('#root').innerHTML=`<div class="app"><aside class="sidebar"><div class="side-brand"><img src="logo.jpg"><div><strong>Geek POS</strong><small>Point of Sale</small></div></div><nav class="nav">${nav()}</nav><div class="side-foot"><div class="user-chip"><strong>${esc(S.user.name)}</strong><span>${S.user.role}</span></div><button id="out" class="btn btn-ghost btn-block" style="margin-top:9px">تسجيل الخروج</button></div></aside><section class="workspace"><header class="topbar"><h2 id="title"></h2><div class="top-actions"><span class="net-dot"></span><span class="muted">${S.shift?'وردية مفتوحة':'لا توجد وردية'}</span><button id="sync" class="btn btn-sm btn-ghost">مزامنة</button></div></header><div id="content" class="content"></div></section></div>`;
  $$('.nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));$('#out').onclick=()=>{S.user=null;login()};$('#sync').onclick=async()=>{const r=await window.geek.sync();toast(r.success?`تمت مزامنة ${r.count} عنصر`:r.message,!r.success)};go('dashboard')
}
async function go(p){if(!roleAllowed(p))return;S.page=p;$$('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const f={dashboard, pos, delivery, shift, reports, products, users, settings, cloud};await f[p]()}
function title(t){$('#title').textContent=t}

async function dashboard(){
  title('لوحة المتابعة');const d=await window.geek.dashboard();
  $('#content').innerHTML=`<div class="grid grid-4"><div class="card kpi"><div class="label">مبيعات اليوم</div><div class="value">${money(d.sales)}</div></div><div class="card kpi"><div class="label">طلبات اليوم</div><div class="value">${d.orders}</div></div><div class="card kpi"><div class="label">طلبات الدليفري</div><div class="value">${d.delivery}</div></div><div class="card kpi"><div class="label">دليفري مفتوح</div><div class="value">${d.openDelivery}</div></div></div><div class="card" style="margin-top:16px"><div class="section-title"><h3>آخر الطلبات</h3><button id="sale" class="btn btn-cyan btn-sm">بيع جديد</button></div><div class="table-wrap"><table class="table"><thead><tr><th>#</th><th>النوع</th><th>الحالة</th><th>الإجمالي</th><th>الوقت</th></tr></thead><tbody>${d.recent.map(o=>`<tr><td>#${o.order_no}</td><td>${TYPE[o.order_type]}</td><td><span class="badge blue">${AR[o.status]}</span></td><td>${money(o.total)}</td><td>${new Date(o.created_at).toLocaleString('ar-EG')}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">لا توجد طلبات</td></tr>'}</tbody></table></div></div>`;$('#sale').onclick=()=>go('pos')
}
async function pos(){
  title('الكاشير');await loadCatalog();let cat='all',mode='takeaway'; const cfg=S.boot?.settings||{};
  const draw=()=>{const prods=cat==='all'?S.products:S.products.filter(p=>p.category_id===cat);const total=S.cart.reduce((s,x)=>s+x.qty*x.price,0);
    $('#content').innerHTML=`<div class="pos-layout"><div class="card catalog"><div class="section-title"><h3>الأصناف</h3><input id="ps" class="input" style="max-width:260px" placeholder="بحث"></div><div class="category-bar"><button class="category-btn ${cat==='all'?'active':''}" data-cat="all">الكل</button>${S.cats.map(c=>`<button class="category-btn ${cat===c.id?'active':''}" data-cat="${c.id}">${esc(c.name)}</button>`).join('')}</div><div class="products">${prods.map(p=>`<button class="product" data-product="${p.id}"><strong>${esc(p.name)}</strong><span class="muted">${esc(p.category_name||'')}</span><span class="price">${money(p.price)}</span></button>`).join('')}</div></div><div class="card cart"><div class="order-modes"><button class="btn ${mode==='takeaway'?'btn-cyan':''}" data-type="takeaway">تيك أواي</button>${cfg.enable_dinein!==false?`<button class="btn ${mode==='dinein'?'btn-cyan':''}" data-type="dinein">صالة</button>`:''}${cfg.enable_delivery!==false?'<button class="btn" data-type="delivery">دليفري</button>':''}</div><div class="cart-items">${S.cart.map((i,k)=>`<div class="cart-row"><div><b>${esc(i.name)}</b><div class="muted">${money(i.price)}</div></div><div class="qty"><button data-minus="${k}">−</button><b>${i.qty}</b><button data-plus="${k}">+</button></div><div>${money(i.qty*i.price)}</div></div>`).join('')||'<div class="empty">اختر الأصناف</div>'}</div><div class="cart-total"><div class="total-line"><span>الإجمالي</span><span class="grand">${money(total)}</span></div><button id="finish" class="btn btn-primary btn-block" ${S.cart.length?'':'disabled'}>إتمام الطلب</button></div></div></div>`;
    $$('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;draw()});$$('[data-product]').forEach(b=>b.onclick=()=>{const p=S.products.find(x=>x.id===b.dataset.product),e=S.cart.find(x=>x.id===p.id);e?e.qty++:S.cart.push({id:p.id,name:p.name,price:Number(p.price),qty:1});draw()});$$('[data-plus]').forEach(b=>b.onclick=()=>{S.cart[+b.dataset.plus].qty++;draw()});$$('[data-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.minus;S.cart[i].qty--;if(S.cart[i].qty<=0)S.cart.splice(i,1);draw()});$('[data-type]').forEach(b=>b.onclick=()=>{if(b.dataset.type==='delivery')return go('delivery');mode=b.dataset.type;draw()});$('#ps').oninput=e=>$$('[data-product]').forEach(b=>b.style.display=b.textContent.includes(e.target.value)?'':'');$('#finish').onclick=async()=>{if(!S.shift)return toast('افتح وردية أولاً',true);const o=await window.geek.orders.create({order_type:mode,user_id:S.user.id,shift_id:S.shift.id,status:'closed',paid:total,items:S.cart.map(x=>({product_id:x.id,product_name:x.name,qty:x.qty,unit_price:x.price}))});S.cart=[];toast('تم حفظ الطلب #'+o.order_no);draw()}
  };draw()
}

async function delivery(){
  title('إدارة الدليفري');const tabs=[['orders','طلبات الدليفري'],['new','طلب جديد'],['customers','العملاء'],['settlement','تسوية الطيار']];
  $('#content').innerHTML=`<div class="tabs">${tabs.map(t=>`<button class="tab ${S.deliveryTab===t[0]?'active':''}" data-tab="${t[0]}">${t[1]}</button>`).join('')}</div><div id="dbody"></div>`;$$('[data-tab]').forEach(b=>b.onclick=()=>{S.deliveryTab=b.dataset.tab;delivery()});
  if(S.deliveryTab==='new')return newDelivery();
  if(S.deliveryTab==='customers')return customers();
  const [orders,drivers]=await Promise.all([window.geek.orders.list('delivery'),window.geek.drivers.list()]);
  if(S.deliveryTab==='settlement')return settlement(orders);
  $('#dbody').innerHTML=`<div class="delivery-shell"><div class="card delivery-list"><input id="dq" class="input" placeholder="بحث بالعميل / المنطقة / رقم الطلب"><div class="compact-list" style="margin-top:10px">${orders.map(o=>`<button class="order-card" data-oid="${o.id}"><div><b>#${o.order_no} — ${esc(o.customer_name||'بدون اسم')}</b><small>${esc(o.area||'')} · ${new Date(o.created_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}</small></div><div><div class="amount">${money(o.total)}</div><span class="badge blue">${AR[o.status]}</span></div></button>`).join('')||'<div class="empty">لا توجد طلبات</div>'}</div></div><div id="detail" class="card delivery-detail"><div class="detail-empty">اختر طلباً</div></div></div>`;
  $$('[data-oid]').forEach(b=>b.onclick=async()=>detail(await window.geek.orders.get(b.dataset.oid),drivers));$('#dq').oninput=e=>$$('[data-oid]').forEach(b=>b.style.display=b.textContent.includes(e.target.value)?'':'')
}
function detail(o,drivers){
  $('#detail').innerHTML=`<div class="section-title"><div><h3>طلب #${o.order_no}</h3><span class="badge blue">${AR[o.status]}</span></div><b class="grand">${money(o.total)}</b></div><div class="customer-hero"><div><strong>${esc(o.customer_name||'')}</strong><div class="muted">${esc(o.customer_mobile||'')} — ${esc(o.area||'')}</div><div>${esc(o.address||'')}</div></div></div><div class="mini-items">${o.items.map(i=>`<div class="mini-item"><b>${esc(i.product_name)}</b><span>${i.qty}</span><span>${money(i.total)}</span><span></span></div>`).join('')}</div><div class="actions" style="margin-top:15px"><button class="btn btn-cyan" data-st="kitchen">إرسال المطبخ</button><button class="btn" data-st="ready">جاهز</button><select id="driver" class="select" style="max-width:180px"><option value="">اختر الطيار</option>${drivers.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select><button id="load" class="btn btn-primary">تحميل الطيار</button><button class="btn btn-green" data-st="closed">تسوية</button><button class="btn btn-red" data-st="returned">مرتجع</button></div>`;
  $$('[data-st]').forEach(b=>b.onclick=async()=>{await window.geek.orders.status(o.id,b.dataset.st,{});toast('تم تحديث الحالة');delivery()});$('#load').onclick=async()=>{if(!$('#driver').value)return toast('اختر الطيار',true);await window.geek.orders.status(o.id,'with_driver',{driver_id:$('#driver').value});toast('تم تحميل الطلب');delivery()}
}
async function newDelivery(){
  await loadCatalog();let items=[];
  $('#dbody').innerHTML=`<div class="card"><div class="section-title"><h3>طلب دليفري جديد</h3><span class="muted">رقم الموبايل أولاً</span></div><div class="form-grid"><div class="field"><label>رقم الموبايل</label><input id="cm" class="input" dir="ltr"></div><div class="field"><label>الاسم</label><input id="cn" class="input"></div><div class="field"><label>المنطقة</label><input id="ca" class="input"></div><div class="field"><label>العنوان</label><input id="cad" class="input"></div><div class="field wide"><label>ملاحظات العميل</label><input id="cno" class="input"></div></div><div class="picker"><select id="ip" class="select">${S.products.map(p=>`<option value="${p.id}">${esc(p.name)} — ${money(p.price)}</option>`).join('')}</select><input id="iq" class="input" type="number" min="1" value="1"><button id="add" class="btn btn-cyan">إضافة</button></div><div id="ilist" class="mini-items"><div class="empty">لم تتم إضافة أصناف</div></div><div class="form-grid"><div class="field"><label>رسوم التوصيل</label><input id="fee" type="number" class="input" value="0"></div><div class="field"><label>ملاحظات الطلب</label><input id="ono" class="input"></div></div><button id="save" class="btn btn-primary">حفظ الطلب</button></div>`;
  const redraw=()=>$('#ilist').innerHTML=items.length?items.map((i,k)=>`<div class="mini-item"><b>${esc(i.product_name)}</b><span>${i.qty}</span><span>${money(i.qty*i.unit_price)}</span><button class="btn btn-red btn-sm" data-rm="${k}">×</button></div>`).join(''):'<div class="empty">لم تتم إضافة أصناف</div>';
  $('#cm').onblur=async()=>{const c=await window.geek.customers.find($('#cm').value);if(c){$('#cn').value=c.name||'';$('#cno').value=c.notes||'';const a=c.addresses?.[0];$('#ca').value=a?.area||'';$('#cad').value=a?.address||'';toast('تم العثور على العميل')}};
  $('#add').onclick=()=>{const p=S.products.find(x=>x.id===$('#ip').value);items.push({product_id:p.id,product_name:p.name,qty:Number($('#iq').value||1),unit_price:Number(p.price)});redraw()};
  $('#ilist').onclick=e=>{if(e.target.dataset.rm!==undefined){items.splice(+e.target.dataset.rm,1);redraw()}};
  $('#save').onclick=async()=>{if(!S.shift)return toast('افتح وردية أولاً',true);if(!$('#cm').value||!$('#cn').value||!items.length)return toast('أكمل بيانات العميل والأصناف',true);const c=await window.geek.customers.save({name:$('#cn').value,mobile:$('#cm').value,area:$('#ca').value,address:$('#cad').value,notes:$('#cno').value});const o=await window.geek.orders.create({order_type:'delivery',customer_id:c.id,address_id:c.addresses?.[0]?.id,user_id:S.user.id,shift_id:S.shift.id,status:'new',delivery_fee:Number($('#fee').value||0),notes:$('#ono').value,items});toast('تم إنشاء طلب #'+o.order_no);S.deliveryTab='orders';delivery()}
}
async function customers(){
  $('#dbody').innerHTML=`<div class="card"><div class="toolbar"><input id="cq" class="input" placeholder="بحث بالاسم / الموبايل / العنوان / المنطقة"><button id="xlsx" class="btn btn-green">تصدير Excel</button></div><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>الموبايل</th><th>العنوان</th><th>المنطقة</th><th>الطلبات</th><th>إجمالي التعامل</th><th>آخر طلب</th></tr></thead><tbody id="crows"></tbody></table></div></div>`;
  const draw=async()=>{const r=await window.geek.customers.list($('#cq').value);$('#crows').innerHTML=r.map(c=>`<tr><td>${esc(c.name)}</td><td dir="ltr">${esc(c.mobile)}</td><td>${esc(c.address||'')}</td><td>${esc(c.area||'')}</td><td>${c.order_count}</td><td>${money(c.total_spent)}</td><td>${c.last_order?new Date(c.last_order).toLocaleDateString('ar-EG'):'—'}</td></tr>`).join('')};$('#cq').oninput=draw;$('#xlsx').onclick=async()=>{const r=await window.geek.customers.export();if(r.success)toast('تم تصدير Excel')};draw()
}
function settlement(orders){
  const x=orders.filter(o=>['with_driver','awaiting_settlement'].includes(o.status));
  $('#dbody').innerHTML=`<div class="card"><div class="section-title"><h3>تسوية الطيار</h3><span class="muted">أغلق الطلبات التي تم تحصيلها فقط</span></div><div class="table-wrap"><table class="table"><thead><tr><th></th><th>#</th><th>الطيار</th><th>العميل</th><th>القيمة</th></tr></thead><tbody>${x.map(o=>`<tr><td><input class="ck" type="checkbox" value="${o.id}"></td><td>#${o.order_no}</td><td>${esc(o.driver_name||'')}</td><td>${esc(o.customer_name||'')}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></div><div class="actions" style="margin-top:14px"><button id="settle" class="btn btn-green">استلام الكاش وإغلاق المحدد</button><button id="ret" class="btn btn-red">مرتجع</button></div></div>`;
  const bulk=async s=>{const ids=$$('.ck:checked').map(c=>c.value);if(!ids.length)return toast('اختر طلباً',true);for(const id of ids)await window.geek.orders.status(id,s,{});toast('تمت العملية');delivery()};$('#settle').onclick=()=>bulk('closed');$('#ret').onclick=()=>bulk('returned')
}

async function shift(){
  title('الورديات');S.shift=await window.geek.shifts.current(S.user.id);
  $('#content').innerHTML=`<div class="grid grid-2"><div class="card"><h3>${S.shift?'الوردية الحالية':'فتح وردية'}</h3>${S.shift?`<p>بدأت: ${new Date(S.shift.opened_at).toLocaleString('ar-EG')}</p><div class="field"><label>نقدية الإغلاق</label><input id="cc" class="input" type="number"></div><button id="close" class="btn btn-red">إغلاق الوردية</button>`:`<div class="field"><label>عهدة البداية</label><input id="oc" class="input" type="number" value="0"></div><button id="open" class="btn btn-green">فتح وردية</button>`}</div><div class="card"><h3>مصروف</h3><div class="field"><label>البند</label><input id="et" class="input"></div><div class="field"><label>القيمة</label><input id="ea" class="input" type="number"></div><button id="exp" class="btn btn-primary" ${S.shift?'':'disabled'}>حفظ المصروف</button></div></div>`;
  if(S.shift)$('#close').onclick=async()=>{await window.geek.shifts.close(S.shift.id,$('#cc').value,'');S.shift=null;toast('تم إغلاق الوردية');shift()};else $('#open').onclick=async()=>{S.shift=await window.geek.shifts.open(S.user.id,$('#oc').value);toast('تم فتح الوردية');shift()};$('#exp').onclick=async()=>{await window.geek.expenses.add({shift_id:S.shift.id,user_id:S.user.id,title:$('#et').value,amount:$('#ea').value});toast('تم حفظ المصروف')}
}
async function reports(){
  title('التقارير');const o=await window.geek.orders.list(),closed=o.filter(x=>x.status==='closed'),sum=closed.reduce((s,x)=>s+Number(x.total||0),0);
  $('#content').innerHTML=`<div class="grid grid-4"><div class="card kpi"><div class="label">إجمالي المبيعات</div><div class="value">${money(sum)}</div></div><div class="card kpi"><div class="label">متوسط الفاتورة</div><div class="value">${money(closed.length?sum/closed.length:0)}</div></div><div class="card kpi"><div class="label">طلبات مغلقة</div><div class="value">${closed.length}</div></div><div class="card kpi"><div class="label">مرتجعات</div><div class="value">${o.filter(x=>x.status==='returned').length}</div></div></div>`
}
async function products(){
  title('الأقسام والأصناف');await loadCatalog();
  $('#content').innerHTML=`<div class="split"><div class="card"><div class="section-title"><h3>الأقسام</h3><button id="newc" class="btn btn-cyan btn-sm">قسم جديد</button></div>${S.cats.map(c=>`<div class="order-card"><b>${esc(c.name)}</b><span>${c.sort_order}</span></div>`).join('')}</div><div class="card"><div class="section-title"><h3>الأصناف</h3><button id="newp" class="btn btn-cyan btn-sm">صنف جديد</button></div><div class="table-wrap"><table class="table"><thead><tr><th>الصنف</th><th>القسم</th><th>السعر</th></tr></thead><tbody>${S.products.map(p=>`<tr><td>${esc(p.name)}</td><td>${esc(p.category_name||'')}</td><td>${money(p.price)}</td></tr>`).join('')}</tbody></table></div></div></div>`;
  $('#newc').onclick=async()=>{const n=prompt('اسم القسم');if(n){await window.geek.saveCategory({name:n,sort_order:S.cats.length+1});products()}};
  $('#newp').onclick=async()=>{const n=prompt('اسم الصنف');if(!n)return;const price=prompt('السعر','0');await window.geek.saveProduct({name:n,price,category_id:S.cats[0]?.id});products()}
}
async function users(){
  title('المستخدمون والصلاحيات');const u=await window.geek.users.list();
  $('#content').innerHTML=`<div class="card"><div class="section-title"><h3>المستخدمون</h3><button id="nu" class="btn btn-cyan">مستخدم جديد</button></div><div class="table-wrap"><table class="table"><thead><tr><th>الاسم</th><th>المستخدم</th><th>الصلاحية</th><th>الحالة</th></tr></thead><tbody>${u.map(x=>`<tr><td>${esc(x.name)}</td><td dir="ltr">${esc(x.username)}</td><td>${esc(x.role)}</td><td>${x.active?'فعال':'موقوف'}</td></tr>`).join('')}</tbody></table></div></div>`;
  $('#nu').onclick=async()=>{const name=prompt('الاسم');if(!name)return;const username=prompt('اسم المستخدم');const password=prompt('كلمة المرور');const role=prompt('الصلاحية: admin أو cashier','cashier');try{await window.geek.users.create({name,username,password,role,permissions:{}});toast('تم إنشاء المستخدم');users()}catch(e){toast(e.message,true)}}
}
async function settings(){
  title('الإعدادات');const s=await window.geek.settings.get(),printers=await window.geek.printers.list();
  $('#content').innerHTML=`<div class="grid grid-2"><div class="card"><h3>النشاط والطباعة</h3><div class="field"><label>اسم النشاط</label><input id="bn" class="input" value="${esc(s.business_name||'')}"></div><label class="check"><input id="dine" type="checkbox" ${s.enable_dinein!==false?'checked':''}> تفعيل الصالة</label><label class="check"><input id="del" type="checkbox" ${s.enable_delivery!==false?'checked':''}> تفعيل الدليفري</label><div class="field"><label>الطابعة الافتراضية</label><select id="pr" class="select"><option value="">اختيار تلقائي</option>${printers.map(p=>`<option value="${esc(p.name)}">${esc(p.displayName||p.name)}</option>`).join('')}</select></div><button id="sl" class="btn btn-primary">حفظ</button></div><div class="card"><h3>Supabase</h3><div class="field"><label>URL</label><input id="su" class="input" dir="ltr" value="${esc(s.supabase_url||S.boot.supabaseDefault.url)}"></div><div class="field"><label>Publishable Key</label><input id="sk" class="input" dir="ltr" value="${esc(s.supabase_key||S.boot.supabaseDefault.key)}"></div><div class="field"><label>Email</label><input id="se" class="input" dir="ltr" value="${esc(s.supabase_email||'')}"></div><div class="field"><label>Password</label><input id="sp" type="password" class="input" dir="ltr"></div><div class="field"><label>Branch ID</label><input id="sb" class="input" dir="ltr" value="${esc(s.branch_id||'')}"></div><button id="sc" class="btn btn-cyan">حفظ واختبار</button></div></div>`;
  $('#sl').onclick=async()=>{await window.geek.settings.save({business_name:$('#bn').value,enable_dinein:$('#dine').checked,enable_delivery:$('#del').checked,default_printer:$('#pr').value});toast('تم الحفظ')};$('#sc').onclick=async()=>{const x={supabase_url:$('#su').value,supabase_key:$('#sk').value,supabase_email:$('#se').value,branch_id:$('#sb').value};if($('#sp').value)x.supabase_password=$('#sp').value;await window.geek.settings.save(x);const r=await window.geek.sync();toast(r.success?'تم الربط والمزامنة':r.message,!r.success)}
}
async function cloud(){
  title('اللوحة السحابية');$('#content').innerHTML=`<div class="card"><h3>Geek POS Online</h3><p class="muted">تم تجهيز لوحة HTML مستقلة لإدارة العملاء والمبيعات والتراخيص حسب صلاحية الحساب، وتعمل مع نفس مشروع Supabase.</p></div>`
}
boot().catch(e=>{document.body.innerHTML='<div class="auth-shell"><div class="auth-card"><h1>تعذر تشغيل Geek POS</h1><p>'+esc(e.message)+'</p></div></div>'});
